import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
df = pd.read_csv("Life Expectancy Data v2.csv")
print(df.head())
print("Shape of the dataset:", df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())
df = df.fillna(df.mean(numeric_only=True))
df.hist(bins=20, figsize=(15, 10))
plt.suptitle("Histogram of Numeric Features")
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 5))
sns.boxplot(y='Life expectancy (men)', data=df)
plt.title("Boxplot of Life Expectancy (Men)")
plt.show()
plt.figure(figsize=(8, 5))
sns.boxplot(y='Life expectancy(women)', data=df)
plt.title("Boxplot of Life Expectancy (Women)")
plt.show()
corr_matrix = df.corr(numeric_only=True)
plt.figure(figsize=(16, 15))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
fig1 = px.scatter(df, x='GDP', y='Life expectancy (men)', color='Status',
                  title="GDP vs Life Expectancy (Men)")
fig1.show()
fig2 = px.scatter(df, x='GDP', y='Life expectancy(women)', color='Status',
                  title="GDP vs Life Expectancy (Women)")
fig2.show()
plt.figure(figsize=(8, 5))
sns.boxplot(x='Status', y='Life expectancy (men)', data=df)
plt.title("Life Expectancy (Men) by Status")
plt.show()
plt.figure(figsize=(8, 5))
sns.boxplot(x='Status', y='Life expectancy(women)', data=df)
plt.title("Life Expectancy (Women) by Status")
plt.show()
